#!/bin/bash
# Claude Sidecar Repo Review
# Analyzes a project repo and generates an organization review
# stored in a .sidecar-reviews/ directory within the project

set -e

REPO_PATH="${1:-.}"
REPO_PATH=$(cd "$REPO_PATH" && pwd)
REPO_NAME=$(basename "$REPO_PATH")
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

REVIEW_DIR="$REPO_PATH/.sidecar-reviews"
mkdir -p "$REVIEW_DIR"

REVIEW_FILE="$REVIEW_DIR/review_${TIMESTAMP}.md"

echo "Scanning $REPO_NAME..."

# Collect repo stats
FILE_COUNT=$(find "$REPO_PATH" -type f \
  -not -path '*/node_modules/*' \
  -not -path '*/.git/*' \
  -not -path '*/dist/*' \
  -not -path '*/.next/*' \
  -not -path '*/__pycache__/*' \
  -not -path '*/.cache/*' | wc -l | tr -d ' ')

DIR_COUNT=$(find "$REPO_PATH" -type d \
  -not -path '*/node_modules/*' \
  -not -path '*/.git/*' \
  -not -path '*/dist/*' \
  -not -path '*/.next/*' \
  -not -path '*/__pycache__/*' \
  -not -path '*/.cache/*' | wc -l | tr -d ' ')

# Extension breakdown
EXT_BREAKDOWN=$(find "$REPO_PATH" -type f \
  -not -path '*/node_modules/*' \
  -not -path '*/.git/*' \
  -not -path '*/dist/*' \
  -not -path '*/.next/*' \
  -not -path '*/__pycache__/*' \
  -not -path '*/.cache/*' | \
  sed 's/.*\.//' | sort | uniq -c | sort -rn | head -15)

# Top-level structure
TOP_LEVEL=$(ls -1 "$REPO_PATH" | head -30)

# Largest files
LARGEST_FILES=$(find "$REPO_PATH" -type f \
  -not -path '*/node_modules/*' \
  -not -path '*/.git/*' \
  -not -path '*/dist/*' | \
  xargs ls -la 2>/dev/null | sort -k5 -rn | head -10 | awk '{print $5, $NF}')

# Git info
GIT_BRANCH=""
GIT_COMMITS=""
LAST_COMMIT=""
if [ -d "$REPO_PATH/.git" ]; then
  GIT_BRANCH=$(git -C "$REPO_PATH" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
  GIT_COMMITS=$(git -C "$REPO_PATH" rev-list --count HEAD 2>/dev/null || echo "?")
  LAST_COMMIT=$(git -C "$REPO_PATH" log -1 --format="%h %s" 2>/dev/null || echo "unknown")
fi

# Deep directory nesting
DEEP_DIRS=$(find "$REPO_PATH" -type d \
  -not -path '*/node_modules/*' \
  -not -path '*/.git/*' | \
  awk -F/ '{print NF-1, $0}' | sort -rn | head -5)

# Config files present
CONFIGS=""
for f in package.json tsconfig.json pyproject.toml Cargo.toml Makefile Dockerfile docker-compose.yml .env.example README.md CLAUDE.md; do
  if [ -f "$REPO_PATH/$f" ]; then
    CONFIGS="$CONFIGS  - $f\n"
  fi
done

# Write review
cat > "$REVIEW_FILE" << REVIEW
# Sidecar Repo Review: $REPO_NAME

**Generated**: $(date '+%Y-%m-%d %H:%M:%S')
**Path**: \`$REPO_PATH\`

## Overview

| Metric | Value |
|--------|-------|
| Total Files | $FILE_COUNT |
| Total Directories | $DIR_COUNT |
| Git Branch | $GIT_BRANCH |
| Total Commits | $GIT_COMMITS |
| Last Commit | $LAST_COMMIT |

## File Type Breakdown

\`\`\`
$EXT_BREAKDOWN
\`\`\`

## Top-Level Structure

\`\`\`
$TOP_LEVEL
\`\`\`

## Configuration Files Found

$(echo -e "$CONFIGS")

## Largest Files

\`\`\`
$LARGEST_FILES
\`\`\`

## Deepest Directory Nesting

\`\`\`
$DEEP_DIRS
\`\`\`

## Suggestions

> These are automated observations. Review with context.

$(
  # Auto-generate suggestions based on what we found
  if [ "$FILE_COUNT" -gt 200 ]; then
    echo "- **Large codebase** ($FILE_COUNT files). Consider if all files are actively used. Look for dead code."
  fi

  if echo "$EXT_BREAKDOWN" | grep -q "json" && [ "$(echo "$EXT_BREAKDOWN" | grep json | awk '{print $1}')" -gt 20 ]; then
    echo "- **Many JSON files**. Consider consolidating configuration or moving data to a database."
  fi

  if [ ! -f "$REPO_PATH/README.md" ]; then
    echo "- **No README.md** found. Add one to describe the project purpose and setup."
  fi

  if [ ! -f "$REPO_PATH/.gitignore" ] && [ -d "$REPO_PATH/.git" ]; then
    echo "- **No .gitignore** found. Add one to prevent committing build artifacts and secrets."
  fi

  if echo "$DEEP_DIRS" | head -1 | awk '{if ($1 > 8) exit 0; else exit 1}'; then
    echo "- **Deep nesting** detected (8+ levels). Consider flattening directory structure."
  fi

  if [ -f "$REPO_PATH/package.json" ] && [ ! -f "$REPO_PATH/package-lock.json" ] && [ ! -f "$REPO_PATH/yarn.lock" ] && [ ! -f "$REPO_PATH/bun.lockb" ]; then
    echo "- **No lockfile** found for Node.js project. Run \`npm install\` to generate one."
  fi

  echo "- Run this review periodically to track project growth and organization."
)

---
*Generated by Claude Sidecar*
REVIEW

echo "Review saved to: $REVIEW_FILE"
echo ""
cat "$REVIEW_FILE"
